name: aspartec_plus
description: "A simple Flutter application to provide academic advice at ITSCH."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.7
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.1
  reactive_forms: ^17.0.1
  svg_flutter: ^0.0.1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/pictures/
    - assets/logos/
